"""add updated_at and set timestamp defaults

Revision ID: 78be99a45234
Revises: 87b22d769247
Create Date: 2024-11-09 20:25:24.401402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78be99a45234'
down_revision = '87b22d769247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
