"""add ingredient group table

Revision ID: 8736f21290ca
Revises: 5ab5f4b23eb6
Create Date: 2024-11-16 20:04:56.630802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8736f21290ca'
down_revision = '5ab5f4b23eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('howtocook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('img_urls', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_group_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('ingredients_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ingredient_groups', ['ingredient_group_id'], ['id'])
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ingredients_ibfk_1', 'recipes', ['recipe_id'], ['id'])
        batch_op.drop_column('ingredient_group_id')

    op.drop_table('ingredient_groups')
    op.drop_table('howtocook')
    # ### end Alembic commands ###
