"""add column image and description ingredient  table

Revision ID: a62ad1475669
Revises: fbfeb5c85c44
Create Date: 2024-11-19 12:37:59.286335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62ad1475669'
down_revision = 'fbfeb5c85c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
