"""add howtocook_images and relation table

Revision ID: e2a43d803fa7
Revises: 64e07a3484d3
Create Date: 2024-11-19 13:35:35.340108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2a43d803fa7'
down_revision = '64e07a3484d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('howtocook_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('howtocook_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['howtocook_id'], ['howtocook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('howtocook', schema=None) as batch_op:
        batch_op.drop_column('img_urls')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('howtocook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_urls', mysql.VARCHAR(length=255), nullable=True))

    op.drop_table('howtocook_images')
    # ### end Alembic commands ###
